### PR TITLE
Test Swift CI

### PR DESCRIPTION
**Pull request by shahmishal**
Replace this paragraph with a description of your changes and rationale. Provide links to an existing issue or external references/discussions, if appropriate.

### Checklist
- [ ] I've read the [Contribution Guidelines](https://github.com/apple/swift-collections-benchmark#contributing-to-swift-collections-benchmark)
- [ ] My contributions are licensed under the [Swift license](https://swift.org/LICENSE.txt).
- [ ] I've followed the coding style of the rest of the project.
- [ ] I've added tests covering my changes (if appropriate).
- [ ] I've verified that my change compiles and works correctly, and does not break any existing tests.
- [ ] I've updated the documentation (if appropriate).

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Review by lorentey — APPROVED** [review]

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
FYI - @lorentey Linux bot is using Ubuntu 20.04 now.

**Comment by shahmishal** [comment]
@swift-ci test

**Pull request closed without merging**
